apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi-premium
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-dump
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-dump
  template:
    metadata:      
      labels:
        app: node-dump
    spec:
      containers:
      - name: pktdump
        image: 'ubuntu:latest'
        command:
        - bash
        - -c
        - |
          NAME=$(cat /etc/hostname);echo /tmp/$NAME.pcap;apt-get update && apt-get install -y tcpdump;
          tcpdump -C 100 -W 5 -i any -w /mnt/tcpdump/$NAME.pcap
        volumeMounts:
        - name: volume
          mountPath: /mnt/tcpdump
      hostNetwork: true
      hostPID: true
      hostIPC: true
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: my-azurefile