apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: ds-disable-daily-upgrade
  name: disable-daily-upgrade
spec:
  selector:
    matchLabels:
      component: ds-disable-daily-upgrade
  template:
    metadata:
      name: systemd-patch
      labels:
        component: ds-disable-daily-upgrade
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
        - command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --
          - sh
          - -c
          - |
            systemctl status systemd; sleep 1000
        image: alpine
        name: systemd-patch
        securityContext:
          privileged: true   
