kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline
  namespace: default
spec:
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kvname
        nodePublishSecretRef:
          name: secrets-store-creds
    - name: default-token-ts2f2
      secret:
        secretName: default-token-ts2f2
        defaultMode: 420
  containers:
    - name: nginx
      image: nginx
      resources: {}
      volumeMounts:
        - name: secrets-store-inline
          readOnly: true
          mountPath: /mnt/secrets-store
        - name: default-token-ts2f2
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
